
package com.mycompany.proyectoestructuradatos.vista;

import javax.swing.JButton;
import javax.swing.JOptionPane;


public class JFmCrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form JFmAdministrativo
     */
    public JFmCrearUsuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Crear Usuario ");
    }

  



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbhabiltar2 = new javax.swing.JLabel();
        txtOpcion2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbMenuOperador2 = new javax.swing.JLabel();
        lbhabiltar = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lbhabiltar1 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lbhabiltar3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbhabiltar4 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();

        lbhabiltar2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbhabiltar2.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar2.setText("Ingrese su Nombre");
        lbhabiltar2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtOpcion2.setBackground(new java.awt.Color(255, 204, 204));
        txtOpcion2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        lbMenuOperador2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMenuOperador2.setForeground(new java.awt.Color(0, 0, 0));
        lbMenuOperador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuOperador2.setText("Registro");

        lbhabiltar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbhabiltar.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar.setText("Ingrese su Nombre Completo:");
        lbhabiltar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtNombre.setBackground(new java.awt.Color(255, 204, 204));
        txtNombre.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");

        lbhabiltar1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbhabiltar1.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar1.setText("Ingrese su numero de documento:");
        lbhabiltar1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtDocumento.setBackground(new java.awt.Color(255, 204, 204));
        txtDocumento.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        lbhabiltar3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbhabiltar3.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar3.setText("Ingrese su usuario:");
        lbhabiltar3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtUsuario.setBackground(new java.awt.Color(255, 204, 204));
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        lbhabiltar4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        lbhabiltar4.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar4.setText("Ingrese su contraseña:");
        lbhabiltar4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtContrasena.setBackground(new java.awt.Color(255, 204, 204));
        txtContrasena.setToolTipText("");
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbMenuOperador2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbhabiltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbhabiltar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbhabiltar)
                                .addComponent(lbhabiltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(45, 45, 45)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtContrasena)
                                .addComponent(txtDocumento)
                                .addComponent(txtNombre)
                                .addComponent(txtUsuario))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addComponent(lbMenuOperador2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbhabiltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbhabiltar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbhabiltar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(lbhabiltar4))
                .addGap(64, 64, 64)
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmCrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMenuOperador2;
    private javax.swing.JLabel lbhabiltar;
    private javax.swing.JLabel lbhabiltar1;
    private javax.swing.JLabel lbhabiltar2;
    private javax.swing.JLabel lbhabiltar3;
    private javax.swing.JLabel lbhabiltar4;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOpcion2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public String getNombre() {
        return txtNombre.getText();
    }

    public String getDocumento() {
        return txtDocumento.getText();
    }

    public String getUsuario() {
        return txtUsuario.getText();
    }


    public String getContrasena() {
        return txtContrasena.getText();
    }


    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }
    
    public void setBtnSalirVisible(boolean visible) {
        btnSalir.setVisible(visible);
    }
}
