package com.mycompany.proyectoestructuradatos.vista;

import java.util.List;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mycompany.proyectoestructuradatos.vista.componentes.PlaceholderTextField;


public class JFmConsultarPrestamos extends javax.swing.JFrame {


    /**
     * Creates new form JFmMantenimiento
     */
    public JFmConsultarPrestamos() {
        initComponents();
//        this.setVisorVisible(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Libros - Biblioteca");
     

    }
    
//  
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVolverMenu = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lbDatosPrestamo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        btnGenerarDevolucion = new javax.swing.JButton();
        lbIdlibro = new javax.swing.JLabel();
        txtIdPrestamo = new javax.swing.JTextField();
        btnDevolverLibro = new javax.swing.JButton();
        lbMenuOperador4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        btnVolverMenu.setText("Volver al Menu");
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        lbDatosPrestamo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbDatosPrestamo.setForeground(new java.awt.Color(0, 0, 0));
        lbDatosPrestamo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDatosPrestamo.setText("Datos De Devolucion Del Libro");

        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Titulo libro", "Fecha Prestamo", "Nombre Prestamista"
            }
        ));
        jScrollPane1.setViewportView(visor);

        btnGenerarDevolucion.setText("Generar Devolucion");
        btnGenerarDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarDevolucionActionPerformed(evt);
            }
        });

        lbIdlibro.setForeground(new java.awt.Color(0, 0, 0));
        lbIdlibro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbIdlibro.setText("Ingrese El ID del libro a Devolver:");
        lbIdlibro.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtIdPrestamo.setBackground(new java.awt.Color(255, 204, 204));
        txtIdPrestamo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnDevolverLibro.setText("Devolver Un Libro");
        btnDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverLibroActionPerformed(evt);
            }
        });

        lbMenuOperador4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMenuOperador4.setForeground(new java.awt.Color(0, 0, 0));
        lbMenuOperador4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuOperador4.setText("Listado De Libros En Prestamo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnVolverMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(lbDatosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnDevolverLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lbMenuOperador4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbIdlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btnGenerarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVolverMenu)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCerrarSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lbMenuOperador4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolverLibro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbDatosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdlibro)
                    .addComponent(txtIdPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGenerarDevolucion)
                .addGap(105, 105, 105))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGenerarDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarDevolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarDevolucionActionPerformed

    private void btnDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolverLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmConsultarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmConsultarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmConsultarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmConsultarPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmConsultarPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDevolverLibro;
    private javax.swing.JButton btnGenerarDevolucion;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDatosPrestamo;
    private javax.swing.JLabel lbIdlibro;
    private javax.swing.JLabel lbMenuOperador4;
    private javax.swing.JTextField txtIdPrestamo;
    public javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables

    public void setResultado(String resultado) {
        JOptionPane.showMessageDialog(this, resultado);
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnVolverMenu() {
        return btnVolverMenu;
    }

    public JButton getBtnGenerarDevolucion() {
        return btnGenerarDevolucion;
    }

    public JButton getBtnDevolverLibro() {
        return btnDevolverLibro;
    }

    public void actualizarVisor(List<Map<String, Object>> libros) {
        // Primero limpiar el modelo de la tabla actual

//        String[] columnNames = {"Id", "Título del libro"};

//         DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        DefaultTableModel model = (DefaultTableModel) visor.getModel();
        model.setRowCount(0);  // Limpiar filas

        // Asegurar que las columnas existen antes de agregar datos
//    if (model.getColumnCount() == 0) {
//            model.setColumnIdentifiers(new String[]{"ID Libro", "Título"});
//        }
        for (Map<String, Object> libro : libros) {
            model.addRow(new Object[]{
                libro.get("id_prestamo"),
                libro.get("titulo"),
                libro.get("fecha_prestamo"),
                 libro.get("nombre")
            });
//        setVisorVisible(true);
//        visor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        }
        ajustarColumnas();
    }

    private void ajustarColumnas() {
        visor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); // Evita el ajuste automático global

        for (int column = 0; column < visor.getColumnCount(); column++) {
            javax.swing.table.TableColumn tableColumn = visor.getColumnModel().getColumn(column);
            int preferredWidth = 0;
            int maxWidth = 300; // Define un límite para evitar columnas demasiado grandes

            // Recorre todas las filas para calcular el ancho necesario
            for (int row = 0; row < visor.getRowCount(); row++) {
                javax.swing.table.TableCellRenderer cellRenderer = visor.getCellRenderer(row, column);
                java.awt.Component c = visor.prepareRenderer(cellRenderer, row, column);
                preferredWidth = Math.max(preferredWidth, c.getPreferredSize().width);
            }

            // Asegurar que la columna no sea demasiado ancha
            tableColumn.setPreferredWidth(Math.min(preferredWidth + 10, maxWidth));
        }
    }

    public void mostrarBotonDinamico(JButton boton, boolean mostrar) {
        boton.setVisible(mostrar);
    }

    public String getIdPrestamo() {
        return txtIdPrestamo.getText();
    }

 

    public void mostrarComponentes(boolean mostrar) {
        lbIdlibro.setVisible(mostrar);
        txtIdPrestamo.setVisible(mostrar);
        lbDatosPrestamo.setVisible(mostrar);
        btnGenerarDevolucion.setVisible(mostrar);
        btnDevolverLibro.setVisible(!mostrar);
    }
    
    public void ocultarComponentes(boolean mostrar) {
        lbIdlibro.setVisible(mostrar);
        txtIdPrestamo.setVisible(mostrar);
        lbDatosPrestamo.setVisible(mostrar);
        btnGenerarDevolucion.setVisible(mostrar);
        btnDevolverLibro.setVisible(mostrar);
    }

}
