
package com.mycompany.proyectoestructuradatos.vista;

import javax.swing.JButton;



public class JFmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFmAdministrativo
     */
    public JFmMenu() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMenuOperador2 = new javax.swing.JLabel();
        lbhabiltar = new javax.swing.JLabel();
        txtOpcion = new javax.swing.JTextField();
        lbMenuOperador3 = new javax.swing.JLabel();
        lbhabiltar1 = new javax.swing.JLabel();
        lbhabiltar2 = new javax.swing.JLabel();
        lbhabiltar3 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbhabiltar4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        lbMenuOperador2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMenuOperador2.setForeground(new java.awt.Color(0, 0, 0));
        lbMenuOperador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuOperador2.setText("Menu Principal");

        lbhabiltar.setBackground(new java.awt.Color(204, 51, 255));
        lbhabiltar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbhabiltar.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar.setText("1. Buscar Libro");
        lbhabiltar.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        txtOpcion.setBackground(new java.awt.Color(255, 204, 204));
        txtOpcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        lbMenuOperador3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbMenuOperador3.setForeground(new java.awt.Color(0, 0, 0));
        lbMenuOperador3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuOperador3.setText("¿Que acción deseas realizar?");

        lbhabiltar1.setBackground(new java.awt.Color(204, 51, 255));
        lbhabiltar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbhabiltar1.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar1.setText("3. Realizar Devolucion de un libro");
        lbhabiltar1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbhabiltar2.setBackground(new java.awt.Color(204, 51, 255));
        lbhabiltar2.setForeground(new java.awt.Color(255, 0, 51));
        lbhabiltar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar2.setText("ingrese en el recuadro la opcion que desea realizar");
        lbhabiltar2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbhabiltar3.setBackground(new java.awt.Color(204, 51, 255));
        lbhabiltar3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbhabiltar3.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar3.setText("2. Realizar Prestamo de un libro");
        lbhabiltar3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnAceptar.setText("Aceptar");

        btnSalir.setText("Cerrar Sesion");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lbhabiltar4.setBackground(new java.awt.Color(204, 51, 255));
        lbhabiltar4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbhabiltar4.setForeground(new java.awt.Color(0, 0, 0));
        lbhabiltar4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbhabiltar4.setText("4. Consultar mis libros prestados");
        lbhabiltar4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbhabiltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbhabiltar1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbhabiltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbhabiltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lbhabiltar, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(lbMenuOperador2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbMenuOperador3, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(txtOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMenuOperador2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(lbMenuOperador3)
                .addGap(24, 24, 24)
                .addComponent(lbhabiltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbhabiltar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbhabiltar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbhabiltar4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbhabiltar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMenuOperador2;
    private javax.swing.JLabel lbMenuOperador3;
    private javax.swing.JLabel lbhabiltar;
    private javax.swing.JLabel lbhabiltar1;
    private javax.swing.JLabel lbhabiltar2;
    private javax.swing.JLabel lbhabiltar3;
    private javax.swing.JLabel lbhabiltar4;
    private javax.swing.JTextField txtOpcion;
    // End of variables declaration//GEN-END:variables

    public String getOpcion() {
        return txtOpcion.getText();
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }
    
        public void limpiarcampos(){
        txtOpcion.setText("");
    }
}
